add fail clienfd to bug539

diff --git a/bug539 b/bug539
--- a/bug539
+++ b/bug539
@@ -1,47 +1,49 @@
-res=0
-ssh -i $Maxscale_sshkey -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@$Maxscale_IP "$maxdir/bin/maxadmin -pskysql -uadmin -P6603 fail backendfd"
+#!/bin/bash
+
+for fail_command in "fail backendfd" "fail clientfd"
+do
+
+ssh -i $Maxscale_sshkey -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@$Maxscale_IP "$maxdir/bin/maxadmin -pskysql -uadmin -P6603  $fail_command"
 if [ $? != 0 ] ; then 
-	res=1;
+	exit 1
 fi
 ssh -i $Maxscale_sshkey -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@$Maxscale_IP "echo \"show databases;\" | mysql -h 127.0.0.1 -P 4006 -u$repl_User -p$repl_Password -c"
 if [ $? != 0 ] ; then      
-        res=1;
+        exit 1
 fi
 
 ssh -i $Maxscale_sshkey -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@$Maxscale_IP "echo \"show databases;\" | mysql -h 127.0.0.1 -P 4006 -u$repl_User -p$repl_Password -c"
 if [ $? != 0 ] ; then      
-        res=1;
+        exit 1
 fi
 
-ssh -i $Maxscale_sshkey -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@$Maxscale_IP "$maxdir/bin/maxadmin -pskysql -uadmin -P6603 fail backendfd"
+ssh -i $Maxscale_sshkey -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@$Maxscale_IP "$maxdir/bin/maxadmin -pskysql -uadmin -P6603 $fail_command"
 if [ $? != 0 ] ; then
-        res=1;
+        exit 1
 fi
 ssh -i $Maxscale_sshkey -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@$Maxscale_IP "echo \"show databases;\" | mysql -h 127.0.0.1 -P 4008 -u$repl_User -p$repl_Password -c"
 if [ $? != 0 ] ; then
-        res=1;
+        exit 1
 fi
 
 ssh -i $Maxscale_sshkey -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@$Maxscale_IP "echo \"show databases;\" | mysql -h 127.0.0.1 -P 4008 -u$repl_User -p$repl_Password -c"
 if [ $? != 0 ] ; then
-        res=1;
+        exit 1
 fi
 
-ssh -i $Maxscale_sshkey -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@$Maxscale_IP "$maxdir/bin/maxadmin -pskysql -uadmin -P6603 fail backendfd"
+ssh -i $Maxscale_sshkey -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@$Maxscale_IP "$maxdir/bin/maxadmin -pskysql -uadmin -P6603 $fail_command"
 if [ $? != 0 ] ; then
-        res=1;
+        exit 1
 fi
 ssh -i $Maxscale_sshkey -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@$Maxscale_IP "echo \"show databases;\" | mysql -h 127.0.0.1 -P 4009 -u$repl_User -p$repl_Password -c"
 if [ $? != 0 ] ; then
-        res=1;
+        exit 1
 fi
 
 ssh -i $Maxscale_sshkey -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@$Maxscale_IP "echo \"show databases;\" | mysql -h 127.0.0.1 -P 4009 -u$repl_User -p$repl_Password -c"
 if [ $? != 0 ] ; then
-        res=1;
+        exit 1
 fi
 
+done
 
-
-
-exit $res
